/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package ventana;

import colegio.Apoderado;
import colegio.Curso;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.xml.transform.TransformerException;
import reportes.GenerarAlumnoBajoAsistencia;
import reportes.GenerarAlumnoReprobado;
import reportes.GenerarApoderadoPupilos;
import reportes.GenerarInforme;
import reportes.GenerarInformeNotasAsistencia;
import reportes.GenerarInformePlanificacion;
import reportes.GenerarInformeProfesores;
import reportes.XmlTransformer;

/**
 *
 * @author toupa
 */
public class VentanaReportes extends javax.swing.JFrame {

    GenerarInforme informe;
    GenerarInformePlanificacion informePlanif;
    GenerarInformeProfesores informeProfe;
    GenerarAlumnoBajoAsistencia informeBajoAsist;
    GenerarAlumnoReprobado informeAlumReprobado;
    GenerarApoderadoPupilos informeApoderadoPupilos;
    GenerarInformeNotasAsistencia informeNotasAsist;
    Curso[] cursos;
    Apoderado[] apoderados;
    XmlTransformer xmlTransformer;

    /**
     * Creates new form VentanaReportes
     */
    public VentanaReportes(Curso[] cursos, Apoderado[] apoderados) {
        this.cursos = cursos;
        this.apoderados = apoderados;
        this.xmlTransformer = new XmlTransformer();
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jButton1.setText("Informe de Notas");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Promedio Alumnos para Profesor");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Asistencia y Notas");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Alumnos por Asistencia");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Apoderados con mas de un alumno");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Planificacion por alumno");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField1.setText("0.0");

        jButton7.setText("Alumnos Reprobados");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton1)
                    .addComponent(jButton2)
                    .addComponent(jButton3)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap(151, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1)
                .addGap(18, 18, 18)
                .addComponent(jButton2)
                .addGap(18, 18, 18)
                .addComponent(jButton3)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jButton5)
                .addGap(18, 18, 18)
                .addComponent(jButton6)
                .addGap(18, 18, 18)
                .addComponent(jButton7)
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        informe = new GenerarInforme(this.apoderados, this.cursos);
        informe.alumToJson();
        informe.alumToXml();
        try {
            xmlTransformer.GenerarTransformacion("Reportes/Informe_notas/informeGeneralWord.xml",
                    "xsl/Informe_notas/informeGeneral.xsl",
                    "Reportes/Informe_notas/informeGeneral.xml");
            xmlTransformer.GenerarTransformacion("Reportes/Informe_notas/informeGeneralHtml.html",
                    "xsl/Informe_notas/toHtml.xsl",
                    "Reportes/Informe_notas/informeGeneral.xml");
        } catch (IOException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        informeProfe = new GenerarInformeProfesores(this.cursos);
        informeProfe.profeToJson();
        informeProfe.profetoXml();
        try {
            xmlTransformer.GenerarTransformacion("Reportes/Promedio_para_profesor/promedioProfesores.xml",
                    "xsl/Promedio_para_profesor/informeProfesores.xsl",
                    "Reportes/Promedio_para_profesor/informeProfesores.xml");
            xmlTransformer.GenerarTransformacion("Reportes/Promedio_para_profesor/promedioProfesoresHtml.html",
                    "xsl/Promedio_para_profesor/toHtml.xsl",
                    "Reportes/Promedio_para_profesor/informeProfesores.xml");
        } catch (IOException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        informeNotasAsist = new GenerarInformeNotasAsistencia(this.cursos);
        informeNotasAsist.notaAsistenciaToJson();
        informeNotasAsist.notaAsistenciatoXml();
        try {
            xmlTransformer.GenerarTransformacion("Reportes/Asistencia_notas/notaAsistenciaWord.xml",
                    "xsl/Asistencia_notas/toWord.xsl", "Reportes/Asistencia_notas/informeNotaAsistencia.xml");
            xmlTransformer.GenerarTransformacion("Reportes/Asistencia_notas/notaAsistenciaHtml.html",
                    "xsl/Asistencia_notas/toHtml.xsl", "Reportes/Asistencia_notas/informeNotaAsistencia.xml");
        } catch (IOException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        informeBajoAsist = new GenerarAlumnoBajoAsistencia(this.cursos, Double.parseDouble(jTextField1.getText()));
        informeBajoAsist.bajoAsistenciaToJson();
        informeBajoAsist.bajoAsistenciaToXml();
        try {
            xmlTransformer.GenerarTransformacion("Reportes/Alumno_por_asistencia/bajoAsistenciaWord.xml",
                    "xsl/Alumno_por_asistencia/bajoAsistencia.xsl",
                    "Reportes/Alumno_por_asistencia/informeBajoAsistencia.xml");
            xmlTransformer.GenerarTransformacion("Reportes/Alumno_por_asistencia/bajoAsistenciaHtml.html",
                    "xsl/Alumno_por_asistencia/toHtml.xsl",
                    "Reportes/Alumno_por_asistencia/informeBajoAsistencia.xml");
        } catch (IOException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        informeApoderadoPupilos = new GenerarApoderadoPupilos(this.apoderados);
        informeApoderadoPupilos.apoderadoPupilosToJson();
        informeApoderadoPupilos.apoderadoPupilostoXml();
        try {
            xmlTransformer.GenerarTransformacion("Reportes/Apoderados_con_pupilos/apoderadosPupilosWord.xml",
                    "xsl/Apoderados_con_pupilos/apoderadosMasPupilos.xsl",
                    "Reportes/Apoderados_con_pupilos/apoderadoPupilos.xml");
            xmlTransformer.GenerarTransformacion("Reportes/Apoderados_con_pupilos/apoderadosPupilosHtml.html",
                    "xsl/Apoderados_con_pupilos/toHtml.xsl",
                    "Reportes/Apoderados_con_pupilos/apoderadoPupilos.xml");
        } catch (IOException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        informePlanif = new GenerarInformePlanificacion(this.cursos, this.apoderados);
        informePlanif.planifToJson();
        informePlanif.planifToXml();
        try {
            xmlTransformer.GenerarTransformacion("Reportes/Planificacion_por_alumno/planificacionWord.xml",
                    "xsl/Planificacion_por_alumno/toWord.xsl",
                    "Reportes/Planificacion_por_alumno/planificacionPorPupilo.xml");
            xmlTransformer.GenerarTransformacion("Reportes/Planificacion_por_alumno/planificacionHtml.htm",
                    "xsl/Planificacion_por_alumno/toHtml.xsl",
                    "Reportes/Planificacion_por_alumno/planificacionPorPupilo.xml");
        } catch (IOException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        informeAlumReprobado = new GenerarAlumnoReprobado(this.cursos);
        informeAlumReprobado.ReprobadosToXml();
        informeAlumReprobado.ReprobadosToJson();
        try {
            xmlTransformer.GenerarTransformacion("Reportes/Reprobados/ReprobadosWord.xml",
                    "xsl/Reprobados/toWord.xsl",
                    "Reportes/Reprobados/informeReprobados.xml");
            xmlTransformer.GenerarTransformacion("Reportes/Reprobados/ReprobadosHtml.html",
                    "xsl/Reprobados/toHtml.xsl",
                    "Reportes/Reprobados/informeReprobados.xml");
        } catch (IOException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        } catch (TransformerException ex) {
            Logger.getLogger(VentanaReportes.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton7ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
