package ventana;


import colegio.Apoderado;
import colegio.Curso;
import com.google.gson.Gson;
import com.google.gson.GsonBuilder;
import enumLibro.ModuloCurso;
import enumLibro.NivelCurso;
import enumLibro.NombreAsignatura;
import java.io.BufferedReader;
import java.io.BufferedWriter;
import java.io.FileNotFoundException;
import java.io.FileReader;
import java.io.FileWriter;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author toupa
 */
public class VentanaInicio extends javax.swing.JFrame {

    private Curso[] cursos;
    private Apoderado[] apoderados;
    private int cursoSeleccionado;
    private int asignaturaSeleccionada;
    private int alumnoSeleccionado;
    private VentanaAsistencia vAsistencia;
    private VentanaPlanif vPlanif;
    private VentanaNotas vNotas;
    private VentanaAnotacion vAnotacion;
    private VentanaReportes vReportes;

    /**
     * Creates new form VentanaInicio
     */
    public VentanaInicio() {
        this.setTitle("Libro de clases");
        cargarCurso();
        cargarApoderado();
        initComponents();
        jTextField1.setText(this.cursos[this.cursoSeleccionado].getAlumnos()[0].getNombre() + " "
                + this.cursos[this.cursoSeleccionado].getAlumnos()[0].getApellido());
        this.asignaturaSeleccionada = jComboBox3.getSelectedIndex();
        this.buscarApoderado();
        System.out.println(this.asignaturaSeleccionada);

    }
    private void cargarCurso() {
        this.cursoSeleccionado = 0;
        this.asignaturaSeleccionada = 0;

        Gson gson = new GsonBuilder().create();
        BufferedReader bufRead = null;
        try {
            bufRead = new BufferedReader(new FileReader("cursosTotal.json"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.cursos = gson.fromJson(bufRead, Curso[].class);
    }

    private void cargarAlumnado() {
        String[] run = new String[30];
        for (int i = 0; i < 30; i++) {
            run[i] = this.cursos[this.cursoSeleccionado].getAlumnos()[i].getRun();

        }
        jTextField1.setText(this.cursos[this.cursoSeleccionado].getAlumnos()[0].getNombre() + " "
                + this.cursos[this.cursoSeleccionado].getAlumnos()[0].getApellido());
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(run));
        this.buscarApoderado();
    }

    private void cargarApoderado() {
        Gson gson = new GsonBuilder().create();
        BufferedReader bufRead = null;
        try {
            bufRead = new BufferedReader(new FileReader("apoderados.json"));
        } catch (FileNotFoundException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        }
        this.apoderados = gson.fromJson(bufRead, Apoderado[].class);

        for (int i = 0; i < this.apoderados.length; i++) {
            for (int pupilos = 0; pupilos < this.apoderados[i].getPupilos().size(); pupilos++) {
                for (int curso = 0; curso < 16; curso++) {
                    String rutAlum = this.apoderados[i].getPupilos().get(pupilos).getRun();
                    if (this.cursos[curso].estaAlumno(rutAlum)) {
                        this.apoderados[i].getPupilos().set(pupilos, this.cursos[curso].getAlumnoPorRut(rutAlum));
                    }
                }
            }
        }

    }

    private void buscarApoderado() {
        for (int i = 0; i < this.apoderados.length; i++) {
            for (int j = 0; j < this.apoderados[i].getPupilos().size(); j++) {
                if (this.apoderados[i].getPupilos().get(j).getRun().equals(jComboBox4.getSelectedItem())) {
                    jTextField2.setText(this.apoderados[i].getNombre() + " " + this.apoderados[i].getApellido());
                    break;
                }
            }

        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jComboBox1 = new javax.swing.JComboBox<>();
        jComboBox2 = new javax.swing.JComboBox<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jComboBox4 = new javax.swing.JComboBox<>();
        jButton5 = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jButton6 = new javax.swing.JButton();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(NivelCurso.values()));
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jComboBox2.setModel(new javax.swing.DefaultComboBoxModel<>(ModuloCurso.values()));
        jComboBox2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox2ActionPerformed(evt);
            }
        });

        jLabel1.setText("Curso");

        jLabel2.setText("Modulo");

        jLabel3.setText("Asignatura");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(NombreAsignatura.values()));
        jComboBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox3ActionPerformed(evt);
            }
        });

        jButton1.setText("Ingresar planificacion");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Ingresar nota");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Ingresar asistencia");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Anotacion");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel4.setText("Run alumno");

        String[] run = new String[30];
        for(int i=0;i<30;i++){
            run[i] = this.cursos[this.cursoSeleccionado].getAlumnos()[i].getRun();
        }
        jComboBox4.setModel(new javax.swing.DefaultComboBoxModel<>(run));
        jComboBox4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox4ActionPerformed(evt);
            }
        });

        jButton5.setText("Guardar cambios");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jTextField1.setEditable(false);

        jButton6.setText("Salir");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jTextField2.setEditable(false);

        jLabel5.setText("Apoderado");

        jButton7.setText("Reportes");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel3)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 72, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton1)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jButton3))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel4)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addComponent(jLabel5, javax.swing.GroupLayout.Alignment.TRAILING))
                            .addComponent(jButton7))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jButton5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jTextField2, javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextField1, javax.swing.GroupLayout.Alignment.LEADING))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jButton3))
                .addGap(40, 40, 40)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jComboBox3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton2)
                    .addComponent(jLabel4)
                    .addComponent(jComboBox4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 60, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton5)
                    .addComponent(jButton6)
                    .addComponent(jButton7))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        for (int i = 0; i < cursos.length; i++) {
            if (cursos[i].getNivel() == jComboBox1.getSelectedItem()) {
                this.cursoSeleccionado = i;
                if (jComboBox2.getSelectedItem() == ModuloCurso.B) {
                    ++this.cursoSeleccionado;
                }
                break;
            }
        }
        this.cargarAlumnado();
        System.out.println("curso: " + this.cursos[this.cursoSeleccionado + 1].getNivel());
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jComboBox2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox2ActionPerformed
        if (jComboBox2.getSelectedItem() != this.cursos[this.cursoSeleccionado].getModulo()) {
            if (jComboBox2.getSelectedItem() == ModuloCurso.A) {
                this.cursoSeleccionado--;
            } else if (jComboBox2.getSelectedItem() == ModuloCurso.B) {
                this.cursoSeleccionado++;
            }
        }
        this.cargarAlumnado();

        System.out.println("array: " + this.cursoSeleccionado);
        System.out.println(this.cursos[this.cursoSeleccionado].getModulo());
    }//GEN-LAST:event_jComboBox2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (vPlanif == null) {
            vPlanif = new VentanaPlanif(this.cursos[this.cursoSeleccionado].getAsignaturas()[this.asignaturaSeleccionada]);
            vPlanif.setVisible(true);
        } else {
            vPlanif.dispose();
            vPlanif = new VentanaPlanif(this.cursos[this.cursoSeleccionado].getAsignaturas()[this.asignaturaSeleccionada]);
            vPlanif.setVisible(true);
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        if (vAsistencia == null) {
            vAsistencia = new VentanaAsistencia(this.cursos[this.cursoSeleccionado]);
            vAsistencia.setVisible(true);
        } else {
            vAsistencia.dispose();
            vAsistencia = new VentanaAsistencia(this.cursos[this.cursoSeleccionado]);
            vAsistencia.setVisible(true);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        BufferedWriter mbrWriter = null;
        BufferedWriter mbrWriter2 = null;
        try {
            Gson gson = new GsonBuilder().setPrettyPrinting().create();
            String archivo = gson.toJson(this.cursos);
            String archivoApoderado = gson.toJson(this.apoderados);
            mbrWriter = new BufferedWriter(new FileWriter("cursosTotal.json"));
            mbrWriter.write(archivo);
            mbrWriter.close();

            mbrWriter2 = new BufferedWriter(new FileWriter("apoderados.json"));
            mbrWriter2.write(archivoApoderado);
            mbrWriter2.close();
        } catch (IOException ex) {
            Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
        } finally {
            try {
                mbrWriter.close();
                mbrWriter2.close();
            } catch (IOException ex) {
                Logger.getLogger(VentanaInicio.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jComboBox4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox4ActionPerformed
        for (int i = 0; i < 30; i++) {
            if (jComboBox4.getSelectedItem() == this.cursos[this.cursoSeleccionado].getAlumnos()[i].getRun()) {
                this.alumnoSeleccionado = i;
                jTextField1.setText(this.cursos[this.cursoSeleccionado].getAlumnos()[i].getNombre() + " "
                        + this.cursos[this.cursoSeleccionado].getAlumnos()[i].getApellido());
                break;
            }
        }
        this.buscarApoderado();
    }//GEN-LAST:event_jComboBox4ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        System.exit(0);
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        if (vNotas == null) {
            vNotas = new VentanaNotas(this.cursos[this.cursoSeleccionado].getAsignaturas()[this.asignaturaSeleccionada],
                    this.cursos[this.cursoSeleccionado].getAlumnos()[this.alumnoSeleccionado]);
            vNotas.setVisible(true);
        } else {
            vNotas.dispose();
            vNotas = new VentanaNotas(this.cursos[this.cursoSeleccionado].getAsignaturas()[this.asignaturaSeleccionada],
                    this.cursos[this.cursoSeleccionado].getAlumnos()[this.alumnoSeleccionado]);
            vNotas.setVisible(true);
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jComboBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox3ActionPerformed
        for (int i = 0; i < 5; i++) {
            if (jComboBox3.getSelectedItem() == this.cursos[this.cursoSeleccionado].getAsignaturas()[i].getNombre()) {
                this.asignaturaSeleccionada = i;
                break;
            }
        }
    }//GEN-LAST:event_jComboBox3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (vAnotacion == null) {
            vAnotacion = new VentanaAnotacion(this.cursos[this.cursoSeleccionado].getAlumnos()[this.alumnoSeleccionado]);
            vAnotacion.setVisible(true);
        } else {
            vAnotacion.dispose();
            vAnotacion = new VentanaAnotacion(this.cursos[this.cursoSeleccionado].getAlumnos()[this.alumnoSeleccionado]);
            vAnotacion.setVisible(true);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (vReportes == null) {
            vReportes = new VentanaReportes(this.cursos,this.apoderados);
            vReportes.setVisible(true);
        } else {
            vReportes.dispose();
            vReportes = new VentanaReportes(this.cursos,this.apoderados);
            vReportes.setVisible(true);
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentanaInicio.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                VentanaInicio v= new VentanaInicio();
                v.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JComboBox<NivelCurso> jComboBox1;
    private javax.swing.JComboBox<ModuloCurso> jComboBox2;
    private javax.swing.JComboBox<NombreAsignatura> jComboBox3;
    private javax.swing.JComboBox<String> jComboBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    // End of variables declaration//GEN-END:variables
}
